<a href="https://colab.research.google.com/github/inhyuk78/Re-implementation-of-MOLI-By-Hossein-Sharifi-Noghabi-/blob/main/01_data_import_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path_drug_response = '/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/GDSC2_fitted_dose_response_27Oct23.xlsx'
path_gene_expr = '/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Gene_Expression/rnaseq_merged.csv'
path_mutation = '/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Mutation/mutations_all_20260316.csv'
path_CNA = '/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Copy_Number_Aberration/CNV_genes_20250207.csv'

In [ ]:
import pandas as pd
import numpy as np

# **Importing Dataset**

### (i) GDSC2 Drug Response Dataset

In [ ]:
drug_df = pd.read_excel(path_drug_response)

In [ ]:
cols = drug_df.columns
print(cols)

Index(['DATASET', 'NLME_RESULT_ID', 'NLME_CURVE_ID', 'CELL_LINE_NAME',
       'SANGER_MODEL_ID', 'CANCER_TYPE', 'DRUG_ID', 'DRUG_NAME',
       'PUTATIVE_TARGET', 'PATHWAY_NAME', 'MIN_CONC', 'MAX_CONC', 'LN_IC50',
       'AUC', 'RMSE', 'Z_SCORE'],
      dtype='object')

In [ ]:
drug_df_cols = [
    'CELL_LINE_NAME',
    'SANGER_MODEL_ID', # Unique identifier of each cell line
    'CANCER_TYPE',
    'DRUG_ID',
    'DRUG_NAME',
    'PUTATIVE_TARGET',
    'LN_IC50', # Log of concen required to reduce cell viability by 50% (lower = less drug required to reduce)
                ]

drug_df = drug_df[drug_df_cols]
drug_df.head()

,CELL_LINE_NAME,SANGER_MODEL_ID,CANCER_TYPE,DRUG_ID,DRUG_NAME,PUTATIVE_TARGET,LN_IC50
0,PFSK-1,SIDM01132,Other Solid Cancers,1003,Camptothecin,TOP1,-1.463887
1,A673,SIDM00848,Ewing's Sarcoma,1003,Camptothecin,TOP1,-4.869455
2,ES5,SIDM00263,Ewing's Sarcoma,1003,Camptothecin,TOP1,-3.360586
3,ES7,SIDM00269,Ewing's Sarcoma,1003,Camptothecin,TOP1,-5.044940
4,EW-11,SIDM00203,Ewing's Sarcoma,1003,Camptothecin,TOP1,-3.741991

In [ ]:
drug_ids = list(drug_df['SANGER_MODEL_ID'].unique())
print(len(drug_ids))
print(drug_ids)

969
['SIDM01132', 'SIDM00848', 'SIDM00263', 'SIDM00269', 'SIDM00203', 'SIDM01111', 'SIDM00909', 'SIDM00807', 'SIDM01085', 'SIDM01160', 'SIDM01190', 'SIDM00889', 'SIDM00905', 'SIDM00627', 'SIDM00982', 'SIDM00998', 'SIDM00799', 'SIDM00581', 'SIDM01171', 'SIDM01193', 'SIDM01189', 'SIDM00315', 'SIDM00924', 'SIDM01120', 'SIDM00922', 'SIDM00512', 'SIDM00548', 'SIDM00734', 'SIDM00747', 'SIDM00746', 'SIDM00745', 'SIDM00742', 'SIDM00737', 'SIDM00769', 'SIDM00709', 'SIDM00716', 'SIDM00729', 'SIDM00727', 'SIDM00726', 'SIDM00724', 'SIDM01122', 'SIDM00509', 'SIDM00865', 'SIDM00522', 'SIDM00654', 'SIDM00653', 'SIDM00741', 'SIDM00760', 'SIDM00735', 'SIDM00706', 'SIDM00699', 'SIDM00733', 'SIDM00730', 'SIDM00719', 'SIDM00965', 'SIDM01128', 'SIDM01126', 'SIDM01121', 'SIDM01131', 'SIDM00713', 'SIDM01100', 'SIDM01099', 'SIDM01179', 'SIDM00320', 'SIDM00293', 'SIDM00368', 'SIDM00365', 'SIDM00294', 'SIDM01098', 'SIDM00715', 'SIDM00702', 'SIDM00739', 'SIDM01124', 'SIDM01184', 'SIDM01148', 'SIDM01101', 'SIDM00649', 'SIDM00708', 'SIDM01182', 'SIDM01174', 'SIDM01119', 'SIDM00921', 'SIDM00547', 'SIDM00645', 'SIDM00771', 'SIDM00669', 'SIDM00505', 'SIDM01078', 'SIDM00756', 'SIDM00728', 'SIDM01163', 'SIDM00347', 'SIDM00872', 'SIDM00866', 'SIDM00885', 'SIDM00884', 'SIDM00877', 'SIDM00874', 'SIDM00774', 'SIDM00772', 'SIDM00675', 'SIDM00172', 'SIDM00174', 'SIDM00191', 'SIDM00990', 'SIDM00986', 'SIDM00489', 'SIDM00961', 'SIDM00939', 'SIDM00942', 'SIDM00175', 'SIDM00190', 'SIDM00953', 'SIDM00951', 'SIDM00207', 'SIDM00524', 'SIDM00970', 'SIDM00486', 'SIDM00278', 'SIDM01044', 'SIDM00188', 'SIDM00052', 'SIDM00591', 'SIDM00590', 'SIDM00632', 'SIDM00223', 'SIDM00230', 'SIDM00693', 'SIDM00606', 'SIDM00603', 'SIDM00301', 'SIDM01032', 'SIDM01028', 'SIDM01025', 'SIDM01024', 'SIDM00187', 'SIDM00186', 'SIDM00185', 'SIDM00184', 'SIDM00183', 'SIDM00182', 'SIDM00181', 'SIDM00180', 'SIDM00345', 'SIDM00296', 'SIDM00292', 'SIDM00339', 'SIDM00245', 'SIDM00053', 'SIDM00516', 'SIDM00751', 'SIDM00493', 'SIDM00927', 'SIDM01133', 'SIDM00237', 'SIDM00367', 'SIDM00391', 'SIDM00249', 'SIDM00417', 'SIDM01229', 'SIDM01009', 'SIDM00395', 'SIDM00369', 'SIDM00349', 'SIDM00326', 'SIDM00934', 'SIDM00105', 'SIDM00088', 'SIDM00120', 'SIDM00783', 'SIDM00789', 'SIDM00829', 'SIDM00136', 'SIDM00791', 'SIDM00139', 'SIDM00138', 'SIDM00144', 'SIDM00116', 'SIDM00097', 'SIDM00148', 'SIDM00125', 'SIDM00124', 'SIDM00903', 'SIDM00123', 'SIDM00122', 'SIDM00121', 'SIDM00081', 'SIDM00082', 'SIDM00080', 'SIDM00135', 'SIDM00145', 'SIDM00079', 'SIDM00146', 'SIDM00826', 'SIDM00841', 'SIDM00941', 'SIDM00087', 'SIDM00096', 'SIDM00117', 'SIDM00151', 'SIDM00091', 'SIDM00119', 'SIDM00118', 'SIDM00133', 'SIDM00134', 'SIDM00149', 'SIDM00003', 'SIDM00107', 'SIDM00108', 'SIDM00086', 'SIDM00094', 'SIDM00113', 'SIDM00112', 'SIDM00095', 'SIDM00111', 'SIDM00083', 'SIDM00084', 'SIDM00085', 'SIDM00150', 'SIDM00092', 'SIDM00090', 'SIDM00132', 'SIDM00984', 'SIDM00987', 'SIDM00490', 'SIDM01245', 'SIDM00900', 'SIDM00850', 'SIDM00494', 'SIDM00797', 'SIDM00795', 'SIDM00796', 'SIDM00997', 'SIDM00983', 'SIDM00999', 'SIDM01076', 'SIDM00893', 'SIDM00210', 'SIDM00513', 'SIDM00952', 'SIDM00506', 'SIDM00954', 'SIDM00515', 'SIDM00140', 'SIDM00956', 'SIDM00284', 'SIDM00910', 'SIDM00130', 'SIDM00923', 'SIDM00919', 'SIDM00940', 'SIDM00930', 'SIDM00931', 'SIDM00890', 'SIDM00845', 'SIDM00886', 'SIDM00887', 'SIDM00888', 'SIDM00867', 'SIDM00949', 'SIDM00831', 'SIDM00948', 'SIDM00947', 'SIDM00281', 'SIDM00981', 'SIDM00864', 'SIDM01001', 'SIDM00863', 'SIDM00793', 'SIDM00280', 'SIDM00279', 'SIDM01056', 'SIDM01051', 'SIDM01047', 'SIDM00277', 'SIDM00276', 'SIDM01042', 'SIDM00860', 'SIDM00213', 'SIDM00857', 'SIDM01055', 'SIDM00274', 'SIDM01057', 'SIDM00273', 'SIDM00227', 'SIDM00544', 'SIDM01259', 'SIDM00853', 'SIDM01043', 'SIDM00852', 'SIDM01251', 'SIDM01073', 'SIDM00882', 'SIDM00878', 'SIDM00875', 'SIDM00673', 'SIDM00596', 'SIDM00594', 'SIDM00290', 'SIDM00671', 'SIDM00064', 'SIDM00291', 'SIDM00806', 'SIDM00589', 'SIDM00588', 'SIDM00661', 'SIDM00828', 'SIDM00676', 'SIDM00678', 'SIDM00695', 'SIDM00679', 'SIDM00587', 'SIDM00585', 'SIDM00599', 'SIDM00694', 'SIDM01060', 'SIDM01206', 'SIDM01059', 'SIDM00225', 'SIDM00224', 'SIDM01039', 'SIDM01218', 'SIDM00808', 'SIDM01013', 'SIDM01012', 'SIDM00613', 'SIDM01007', 'SIDM01010', 'SIDM01008', 'SIDM01005', 'SIDM00687', 'SIDM01003', 'SIDM00785', 'SIDM00612', 'SIDM01019', 'SIDM01020', 'SIDM00607', 'SIDM00533', 'SIDM00531', 'SIDM00541', 'SIDM00534', 'SIDM00535', 'SIDM00537', 'SIDM00523', 'SIDM00855', 'SIDM00856', 'SIDM00553', 'SIDM00308', 'SIDM01033', 'SIDM00555', 'SIDM00556', 'SIDM01031', 'SIDM01030', 'SIDM01029', 'SIDM01027', 'SIDM01026', 'SIDM00327', 'SIDM00329', 'SIDM00346', 'SIDM00297', 'SIDM00549', 'SIDM00683', 'SIDM00342', 'SIDM00839', 'SIDM00340', 'SIDM00776', 'SIDM00660', 'SIDM00677', 'SIDM01219', 'SIDM00637', 'SIDM01246', 'SIDM00633', 'SIDM00528', 'SIDM00272', 'SIDM00628', 'SIDM00337', 'SIDM00336', 'SIDM00526', 'SIDM00625', 'SIDM00545', 'SIDM00335', 'SIDM00334', 'SIDM00525', 'SIDM00331', 'SIDM00376', 'SIDM00386', 'SIDM00387', 'SIDM00388', 'SIDM00271', 'SIDM00260', 'SIDM00441', 'SIDM00561', 'SIDM00438', 'SIDM00532', 'SIDM00504', 'SIDM00433', 'SIDM00431', 'SIDM01023', 'SIDM00623', 'SIDM00222', 'SIDM00562', 'SIDM00640', 'SIDM00657', 'SIDM00429', 'SIDM00641', 'SIDM00244', 'SIDM00655', 'SIDM00777', 'SIDM01130', 'SIDM01146', 'SIDM01144', 'SIDM01145', 'SIDM00577', 'SIDM00576', 'SIDM00575', 'SIDM00573', 'SIDM00580', 'SIDM00574', 'SIDM01203', 'SIDM00572', 'SIDM00778', 'SIDM00779', 'SIDM01127', 'SIDM00925', 'SIDM01147', 'SIDM00722', 'SIDM00755', 'SIDM00718', 'SIDM00651', 'SIDM00652', 'SIDM00697', 'SIDM00720', 'SIDM00748', 'SIDM00749', 'SIDM00743', 'SIDM00740', 'SIDM00738', 'SIDM00758', 'SIDM00710', 'SIDM00731', 'SIDM01129', 'SIDM01117', 'SIDM00567', 'SIDM00457', 'SIDM00239', 'SIDM00463', 'SIDM00364', 'SIDM00363', 'SIDM01140', 'SIDM00241', 'SIDM00220', 'SIDM00451', 'SIDM00844', 'SIDM00359', 'SIDM00847', 'SIDM00447', 'SIDM01092', 'SIDM01090', 'SIDM00352', 'SIDM00813', 'SIDM00403', 'SIDM01086', 'SIDM00402', 'SIDM00401', 'SIDM01084', 'SIDM00351', 'SIDM01080', 'SIDM00383', 'SIDM00382', 'SIDM01079', 'SIDM00396', 'SIDM01095', 'SIDM01112', 'SIDM01096', 'SIDM01110', 'SIDM01109', 'SIDM01108', 'SIDM00380', 'SIDM01107', 'SIDM01105', 'SIDM01106', 'SIDM00392', 'SIDM01104', 'SIDM01103', 'SIDM00379', 'SIDM01097', 'SIDM01113', 'SIDM00373', 'SIDM01180', 'SIDM01199', 'SIDM01194', 'SIDM00781', 'SIDM00390', 'SIDM01154', 'SIDM00814', 'SIDM01155', 'SIDM00835', 'SIDM00812', 'SIDM00834', 'SIDM00420', 'SIDM01164', 'SIDM00837', 'SIDM01168', 'SIDM01175', 'SIDM00833', 'SIDM01159', 'SIDM00832', 'SIDM01178', 'SIDM01161', 'SIDM00782', 'SIDM00370', 'SIDM00252', 'SIDM00251', 'SIDM01172', 'SIDM01205', 'SIDM00321', 'SIDM01191', 'SIDM00424', 'SIDM01186', 'SIDM01183', 'SIDM00317', 'SIDM01000', 'SIDM00412', 'SIDM00411', 'SIDM00316', 'SIDM00971', 'SIDM00235', 'SIDM00554', 'SIDM01018', 'SIDM00584', 'SIDM00479', 'SIDM01177', 'SIDM01150', 'SIDM01247', 'SIDM00482', 'SIDM00467', 'SIDM00469', 'SIDM00480', 'SIDM00477', 'SIDM00282', 'SIDM00286', 'SIDM01248', 'SIDM00842', 'SIDM00233', 'SIDM00917', 'SIDM00957', 'SIDM00142', 'SIDM00143', 'SIDM00343', 'SIDM00267', 'SIDM00794', 'SIDM00988', 'SIDM01233', 'SIDM01082', 'SIDM00899', 'SIDM00907', 'SIDM00898', 'SIDM00287', 'SIDM00985', 'SIDM00962', 'SIDM00306', 'SIDM00324', 'SIDM00901', 'SIDM00798', 'SIDM00569', 'SIDM01237', 'SIDM00810', 'SIDM00928', 'SIDM01228', 'SIDM01089', 'SIDM00698', 'SIDM00744', 'SIDM01087', 'SIDM01081', 'SIDM01197', 'SIDM01198', 'SIDM01165', 'SIDM01187', 'SIDM01083', 'SIDM00943', 'SIDM00937', 'SIDM00895', 'SIDM00896', 'SIDM00849', 'SIDM00801', 'SIDM00803', 'SIDM00980', 'SIDM00995', 'SIDM00989', 'SIDM00933', 'SIDM00384', 'SIDM00355', 'SIDM00543', 'SIDM00492', 'SIDM00502', 'SIDM00495', 'SIDM00540', 'SIDM00511', 'SIDM00285', 'SIDM00243', 'SIDM00212', 'SIDM00211', 'SIDM00446', 'SIDM00332', 'SIDM00958', 'SIDM00932', 'SIDM01052', 'SIDM00681', 'SIDM00499', 'SIDM00996', 'SIDM00992', 'SIDM00964', 'SIDM00938', 'SIDM00935', 'SIDM00488', 'SIDM01064', 'SIDM00592', 'SIDM00496', 'SIDM00302', 'SIDM00686', 'SIDM01210', 'SIDM00557', 'SIDM00056', 'SIDM00312', 'SIDM00630', 'SIDM00721', 'SIDM00759', 'SIDM01157', 'SIDM01173', 'SIDM00560', 'SIDM00529', 'SIDM01242', 'SIDM00247', 'SIDM01116', 'SIDM00299', 'SIDM00242', 'SIDM01138', 'SIDM01136', 'SIDM01135', 'SIDM01088', 'SIDM00218', 'SIDM01093', 'SIDM00381', 'SIDM00484', 'SIDM00319', 'SIDM00325', 'SIDM00348', 'SIDM00328', 'SIDM00023', 'SIDM00234', 'SIDM00410', 'SIDM00963', 'SIDM00481', 'SIDM00344', 'SIDM00157', 'SIDM01021', 'SIDM00622', 'SIDM00732', 'SIDM00620', 'SIDM00542', 'SIDM00209', 'SIDM00208', 'SIDM00206', 'SIDM00920', 'SIDM00283', 'SIDM00918', 'SIDM00892', 'SIDM00659', 'SIDM00289', 'SIDM00240', 'SIDM00261', 'SIDM00264', 'SIDM00262', 'SIDM00266', 'SIDM00201', 'SIDM00202', 'SIDM00200', 'SIDM00205', 'SIDM00197', 'SIDM00198', 'SIDM00621', 'SIDM00196', 'SIDM00195', 'SIDM00330', 'SIDM00259', 'SIDM00258', 'SIDM00253', 'SIDM00156', 'SIDM00255', 'SIDM00254', 'SIDM00257', 'SIDM00256', 'SIDM00578', 'SIDM00427', 'SIDM00454', 'SIDM00179', 'SIDM01016', 'SIDM00680', 'SIDM00485', 'SIDM00501', 'SIDM00487', 'SIDM00955', 'SIDM01045', 'SIDM00861', 'SIDM01040', 'SIDM00129', 'SIDM00101', 'SIDM00100', 'SIDM00098', 'SIDM00309', 'SIDM00310', 'SIDM00311', 'SIDM00519', 'SIDM00518', 'SIDM00517', 'SIDM00114', 'SIDM00598', 'SIDM01072', 'SIDM01070', 'SIDM01069', 'SIDM01067', 'SIDM00672', 'SIDM00667', 'SIDM00666', 'SIDM00665', 'SIDM01066', 'SIDM00600', 'SIDM00602', 'SIDM00617', 'SIDM00616', 'SIDM00615', 'SIDM00614', 'SIDM00128', 'SIDM00127', 'SIDM00552', 'SIDM00551', 'SIDM00685', 'SIDM00684', 'SIDM01220', 'SIDM00629', 'SIDM00527', 'SIDM00333', 'SIDM00442', 'SIDM00638', 'SIDM00579', 'SIDM00770', 'SIDM00768', 'SIDM00763', 'SIDM00762', 'SIDM00761', 'SIDM00753', 'SIDM00704', 'SIDM00137', 'SIDM01125', 'SIDM01134', 'SIDM01149', 'SIDM00565', 'SIDM01141', 'SIDM00564', 'SIDM00466', 'SIDM00465', 'SIDM00453', 'SIDM00361', 'SIDM00270', 'SIDM00115', 'SIDM00473', 'SIDM00358', 'SIDM00426', 'SIDM00394', 'SIDM00377', 'SIDM01181', 'SIDM01188', 'SIDM00371', 'SIDM01162', 'SIDM00419', 'SIDM01169', 'SIDM00418', 'SIDM00318', 'SIDM00975', 'SIDM01176', 'SIDM00046', 'SIDM01240', 'SIDM00462', 'SIDM00491', 'SIDM00077', 'SIDM00078', 'SIDM00936', 'SIDM00929', 'SIDM00051', 'SIDM00050', 'SIDM00944', 'SIDM00199', 'SIDM00950', 'SIDM01002', 'SIDM00503', 'SIDM00858', 'SIDM00104', 'SIDM00103', 'SIDM00102', 'SIDM00099', 'SIDM00154', 'SIDM00520', 'SIDM00881', 'SIDM01068', 'SIDM01062', 'SIDM00994', 'SIDM00993', 'SIDM00510', 'SIDM00521', 'SIDM00946', 'SIDM01048', 'SIDM00859', 'SIDM00846', 'SIDM00670', 'SIDM00664', 'SIDM00663', 'SIDM00662', 'SIDM00586', 'SIDM00618', 'SIDM00690', 'SIDM01037', 'SIDM00126', 'SIDM00619', 'SIDM00611', 'SIDM00609', 'SIDM00604', 'SIDM00583', 'SIDM00582', 'SIDM00571', 'SIDM00550', 'SIDM00300', 'SIDM00341', 'SIDM00658', 'SIDM00750', 'SIDM00792', 'SIDM00754', 'SIDM00703', 'SIDM00700', 'SIDM00926', 'SIDM00723', 'SIDM00570', 'SIDM00568', 'SIDM00478', 'SIDM00566', 'SIDM00425', 'SIDM01139', 'SIDM01137', 'SIDM00455', 'SIDM00044', 'SIDM00043', 'SIDM00042', 'SIDM00360', 'SIDM00356', 'SIDM00354', 'SIDM00353', 'SIDM00350', 'SIDM00399', 'SIDM00375', 'SIDM00041', 'SIDM01156', 'SIDM00322', 'SIDM00040', 'SIDM01170', 'SIDM01077', 'SIDM00976', 'SIDM00974', 'SIDM00973', 'SIDM00854', 'SIDM01058', 'SIDM00879', 'SIDM01071', 'SIDM01261', 'SIDM00176', 'SIDM00508', 'SIDM00507', 'SIDM00668', 'SIDM00045', 'SIDM00428', 'SIDM01038', 'SIDM01036', 'SIDM00689', 'SIDM00688', 'SIDM01015', 'SIDM01011', 'SIDM01017', 'SIDM01006', 'SIDM01004', 'SIDM01034', 'SIDM00313', 'SIDM00631', 'SIDM00338', 'SIDM00437', 'SIDM00435', 'SIDM00434', 'SIDM01217', 'SIDM00646', 'SIDM00766', 'SIDM00711', 'SIDM01123', 'SIDM01201', 'SIDM00443', 'SIDM00461', 'SIDM00460', 'SIDM00458', 'SIDM00362', 'SIDM00450', 'SIDM01114', 'SIDM00449', 'SIDM00448', 'SIDM00415', 'SIDM00374', 'SIDM00389', 'SIDM00404', 'SIDM00405', 'SIDM00406', 'SIDM00407', 'SIDM00423', 'SIDM00422', 'SIDM00421', 'SIDM00323', 'SIDM00416', 'SIDM01102', 'SIDM00413', 'SIDM01118', 'SIDM00969', 'SIDM00968', 'SIDM00305', 'SIDM00304', 'SIDM00303', 'SIDM00474', 'SIDM00476', 'SIDM00475', 'SIDM00967', 'SIDM00966', 'SIDM00238', 'SIDM00472', 'SIDM00815', 'SIDM01041', 'SIDM00445', 'SIDM00444', 'SIDM00393', 'SIDM00483', 'SIDM00539', 'SIDM00538', 'SIDM00530', 'SIDM00048', 'SIDM00047', 'SIDM00250', 'SIDM01185', 'SIDM00231', 'SIDM00232', 'SIDM00819', 'SIDM00818', 'SIDM00817', 'SIDM00820', 'SIDM00821', 'SIDM00816', 'SIDM00608', 'SIDM01265', 'SIDM00459', 'SIDM00217', 'SIDM00216', 'SIDM00215', 'SIDM00214', 'SIDM00194', 'SIDM00193', 'SIDM00498', 'SIDM00049', 'SIDM00870']

### (ii) Gene Expression Dataset

In [ ]:
chunks = []

gene_expr_cols = ['model_name', 'model_id', 'gene_symbol', 'rsem_tpm']

for chunk in pd.read_csv(path_gene_expr,chunksize=500_000):
  filtered = chunk[chunk['model_id'].isin(drug_ids)][gene_expr_cols]

  chunks.append(filtered)

rnaseq_df = pd.concat(chunks, ignore_index=True)
rnaseq_df.head()

  model_name   model_id gene_symbol  rsem_tpm
0     LS-123  SIDM00776        DVL2    3.5521
1    MOLM-13  SIDM00437       STPG1    2.2898
2       HARA  SIDM00598       STPG1    2.9486
3    HCC-366  SIDM01070       STPG1    2.4906
4    MV-4-11  SIDM00657       STPG1    1.3674

In [ ]:
print(rnaseq_df.shape)

(36392676, 4)

In [ ]:
missing = rnaseq_df.isna().mean().sort_values(ascending=False)
missing

rsem_tpm       0.003713
model_name     0.000000
model_id       0.000000
gene_symbol    0.000000
dtype: float64

In [ ]:
print(f"Before: {rnaseq_df.shape}")

rnaseq_df = rnaseq_df.dropna()

print(f"After: {rnaseq_df.shape}")

Before: (36392676, 4)
After: (36257567, 4)

### (iii) Mutation Dataset

In [ ]:
chunks = []

mutation_cols = ['model_name', 'model_id', 'gene_symbol', 'cancer_driver', 'effect']

for chunk in pd.read_csv(path_mutation, chunksize=500_00):
  filtered = chunk[chunk['model_id'].isin(drug_ids)][mutation_cols]

  chunks.append(filtered)

mutation_df = pd.concat(chunks, ignore_index=True)
mutation_df.head()

/tmp/ipykernel_756/3596565142.py:5: DtypeWarning: Columns (2,8,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path_mutation, chunksize=500_00):

  model_name   model_id gene_symbol cancer_driver      effect
0      GR-ST  SIDM01259       TEKT4             f  ess_splice
1      GR-ST  SIDM01259       EIF5B             f  frameshift
2      GR-ST  SIDM01259       NPHP1             f    intronic
3      GR-ST  SIDM01259       NPHP1             f  frameshift
4      GR-ST  SIDM01259   MIR1302-3             f  nc_variant

In [ ]:
mutation_df['cancer_driver'] = mutation_df['cancer_driver'].map({'t':1, 'f':0})
mutation_df['cancer_driver'].unique()

array([0, 1])

### (iv) Copy Number Aberration (CNA) Dataset

In [ ]:
chunks = []

CNA_cols = ['model_name', 'model_id', 'symbol', 'total_copy_number', 'cn_category', 'loh', 'focal', 'cancer_driver']

CNA_dtype_dict = {
    'model_id': str,
    'model_name': str,
    'cn_category': str,
    'symbol': str,
    'total_copy_number': 'float64',
    'loh': str,
    'focal': str,
    'cancer_driver': int
}

for chunk in pd.read_csv(path_CNA, chunksize=500_000, dtype=CNA_dtype_dict, low_memory=False):
  filtered = chunk[chunk['model_id'].isin(drug_ids)][CNA_cols]

  chunks.append(filtered)

CNA_df = pd.concat(chunks, ignore_index=True)

In [ ]:
CNA_df['loh'] = CNA_df['loh'].map({'t':1, 'f':0})
CNA_df['focal'] = CNA_df['focal'].map({'t':1, 'f':0})

In [ ]:
print(CNA_df['loh'].unique())
print(CNA_df['focal'].unique())

[nan  0.  1.]
[nan  0.  1.]

In [ ]:
missing = CNA_df.isna().mean().sort_values(ascending=False)
missing

# Roughly 2~3% of data NaN values for loh, focal, total_copy_number

loh                  0.027934
total_copy_number    0.026916
focal                0.026916
model_name           0.000000
symbol               0.000000
model_id             0.000000
cn_category          0.000000
cancer_driver        0.000000
dtype: float64

In [ ]:
print(f"Before: {CNA_df.shape}")

CNA_df = CNA_df.dropna()

print(f"After: {CNA_df.shape}")

Before: (19203438, 8)
After: (18667013, 8)

### Saving pandas DataFrames

In [ ]:
drug_df.to_parquet('/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Dataframes/drug.parquet')
rnaseq_df.to_parquet('/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Dataframes/rnaseq.parquet')
mutation_df.to_parquet('/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Dataframes/mutation.parquet')
CNA_df.to_parquet('/content/drive/MyDrive/Colab_Notebooks/Projects/Paper_to_code/Data/Dataframes/CNA.parquet')